name: 'Destroy ACI'

on:
  workflow_dispatch:
    
env:
  ACI_RESOURCE_GROUP: 'runners-rg'

jobs:
  destroy-aci:
    runs-on: ubuntu-latest
    steps:
      # Login via Azure CLI (required to run Azure CLI commands)
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Delete Azure Container Instance'
        run: |
          az container delete \
            --resource-group "${{ env.ACI_RESOURCE_GROUP }}" \
            --name "${{ github.event.workflow_run.outputs.aci_name }}" \  # Use ACI name from Pipe A output
            --yes