name: 'Destroy ACI'
on:
  workflow_run:
    workflows: 
      - Terraform Plan/Apply
    types:
      - completed
env:
  ACI_RESOURCE_GROUP: 'runners-rg'

jobs:
  destroy-aci:
    runs-on: ubuntu-latest
    steps:
      # Login via Azure CLI (required to run Azure CLI commands)
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Delete Azure Container Instance'
        run: |
          echo "Deleting container with name: ${{ github.event.workflow_run.conclusion }}"
          ACI_NAME=$(echo ${{ github.event.workflow_run.conclusion }} | jq -r '.jobs[0].outputs.aci_name')
          echo "Using ACI name: $ACI_NAME"
          az container delete \
            --resource-group "${{ env.ACI_RESOURCE_GROUP }}" \
            --name "$ACI_NAME" \  # Use ACI name from Pipe A output
            --yes